import { WorkerEntrypoint } from "cloudflare:workers";
import { drizzle } from "drizzle-orm/d1";
import { eq, inArray } from "drizzle-orm";

// Generated by the OpenNext build. The custom entrypoint preserves Next.js
// fetch handling while adding the Dial service and Queue entrypoints.
// @ts-ignore The generated module does not exist until opennext:build.
import handler from "./.open-next/worker.js";
// @ts-ignore The generated module does not exist until opennext:build.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";

import * as schema from "./src/db/schema";
import {
  beginDialConnectionIntentSchema,
  consumeDialConnectionIntentSchema,
  dialBackfillRequestSchema,
  dialEditCapabilityRequestSchema,
  dialRecipeEventSchema,
} from "./src/lib/dial-contract";
import { createDialRepository } from "./src/lib/dial-repository";

function repository(env: CloudflareEnv) {
  return createDialRepository({
    configuration: {
      appOrigin: env.APP_URL,
      dialAppOrigin: env.DIAL_APP_ORIGIN,
    },
    db: drizzle(env.NEXT_TAG_CACHE_D1!, { schema }),
  });
}

export class DialProvider extends WorkerEntrypoint<CloudflareEnv> {
  async beginConnectionIntent(input: unknown) {
    return repository(this.env).beginConnectionIntent(beginDialConnectionIntentSchema.parse(input));
  }

  async consumeConnectionIntent(input: unknown) {
    const parsed = consumeDialConnectionIntentSchema.parse(input);
    return repository(this.env).consumeConnectionIntent(parsed.intentToken);
  }

  async getRecipeBackfill(input: unknown) {
    return repository(this.env).getBackfill(dialBackfillRequestSchema.parse(input));
  }

  async checkEditCapability(input: unknown) {
    return repository(this.env).checkEditCapability(dialEditCapabilityRequestSchema.parse(input));
  }
}

export default {
  fetch: handler.fetch,

  async scheduled(_controller: ScheduledController, env: CloudflareEnv): Promise<void> {
    const db = drizzle(env.NEXT_TAG_CACHE_D1!, { schema });
    const pending = await db.query.dialRecipeEventsTable.findMany({
      where: eq(schema.dialRecipeEventsTable.status, "pending"),
      orderBy: (table, { asc }) => [asc(table.createdAt)],
      limit: 100,
    });
    if (pending.length === 0) return;
    await env.DIAL_RECIPE_EVENTS.sendBatch(pending.map((event) => ({
      body: dialRecipeEventSchema.parse(event.payload),
      contentType: "json" as const,
    })));
    await db.update(schema.dialRecipeEventsTable).set({
      queuedAt: new Date(),
      status: "queued",
    }).where(inArray(schema.dialRecipeEventsTable.id, pending.map((event) => event.id)));
  },
} satisfies ExportedHandler<CloudflareEnv>;
