import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";
import { getSessionFromCookie } from "@/utils/auth";
import { Navigation } from "@/components/navigation";
import { Footer } from "@/components/footer";
import { TooltipProvider } from "@radix-ui/react-tooltip";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSessionFromCookie();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          session={session}
        >
          <TooltipProvider
            delayDuration={100}
            skipDelayDuration={50}
          >
            <div className="min-h-screen flex flex-col">
              <Navigation />
              <main className="flex-1">
                {children}
              </main>
              <Footer />
            </div>

            <Toaster richColors closeButton position="top-right" expand duration={2500} />
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
